name: AquilaCine
version: '0.1.0'
main: de.emn4tor.AquilaCine
api-version: '1.21'
author: Emn4tor

commands:
  cameradrive:
    description: Main command for camera drives
    usage: /cameradrive <list|start|stop|reload|help>
    aliases: [cdrive]
    permission: cameradrives.use

permissions:
  cameradrives.use:
    description: Allows using camera drives
    default: true
  cameradrives.reload:
    description: Allows reloading camera drives
    default: op
